/***************************************************************************

    file        : grcarlight.h
    created     : Sun Oct 26 15:15:11 CET 2003
    copyright   : (C) 2003 by Christophe Guionneau                      
    version     : $Id$                                  

 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 
#define MAX_NUMBER_LIGHT 4+4+4+2
/*
   4 front 
   4 rear
   4 break
   2 reverse
 */
#define LIGHT_TYPE_FRONT		1
#define LIGHT_TYPE_FRONT2		2
#define LIGHT_TYPE_REAR			3
#define LIGHT_TYPE_REAR2		4
#define LIGHT_TYPE_BRAKE		5
#define LIGHT_TYPE_BRAKE2		6
#define LIGHT_TYPE_REVERSE		7
#define LIGHT_NO_TYPE			0

